name: Docs Server CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - docs-server

jobs:
  release:
    name: Publish Docker image
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: name/app # list of Docker images to use as base name for tags
          tag-sha: true # add git short SHA as Docker tag
      - uses: actions/cache@v1
      - uses: docker/setup-buildx-action@v1
      - name: Publish
        uses: docker/build-push-action@v2
        with:
          context: docs-server
          file: ./Dockerfile
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: ${{ steps.docker_meta.outputs.tags }}
          repository: nycodeghg/bankobot/docdex
          tag_with_ref: true
